function y = CIC(x)

%CIC Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 22-Sep-2017 10:33:31

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;
if isempty(Hd)
    
    decf    = 16;  % Decimation Factor
    diffd   = 17;  % Differential Delay
    numsecs = 3;   % Number of Sections
    
    Hd = dsp.CICDecimator( ...
        'DecimationFactor', decf, ...
        'DifferentialDelay', diffd, ...
        'NumSections', numsecs);
end

s = fi(x,1,16,15,'RoundingMethod','Round','OverflowAction','Saturate');

y = step(Hd,s);
release(Hd);



% [EOF]
